---
title: "Data Preprocessing"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Loading the data from CSV file
library(readr)
library(caret)

Emissions_CO2_NO2_df <- read_csv("/Users/sairam/Desktop/IIT files/Subjects/DPA CSP 571/Project Datasets/Emissions_CO2_NO2.csv")

Temperature_Change_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Temperature Change.csv")

Forest_Fires_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Forest Fires.csv")

Forest_Area_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Forest Area.csv")

Agri_Land_Used_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Land usage (agriculture and forest)_EN.csv")

Social_And_Health_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Social and health data.csv")

Credit_To_Agri_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Credit to Agriculture.csv")

Fertilizer_Indicators_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/Fertilizer Indicators Dataset.csv")

GDP_df <- read_csv("/Users/sairam/Library/CloudStorage/OneDrive-IllinoisInstituteofTechnology/DPA Project/Project Datasets/GDP dataset.csv")

```


```{r}
# Emissions_CO2_NO2_df
# dim(Emissions_CO2_NO2_df)
# names(Emissions_CO2_NO2_df)

# Emissions_CO2_NO2_df[1,]
names(Emissions_CO2_NO2_df)[c(1,2,5,6,7,8,13,14)] <- c('Emissions_Domain Code', 'Emissions_Domain', 'Emissions_Element Code', 'Emissions_Element', 'Emissions_Item Code', 'Emissions_Item', 'Emissions_Unit', 'Emissions_Value')
# names(Emissions_CO2_NO2_df)
```
```{r}
# Temperature_Change_df
# dim(Temperature_Change_df)
# names(Temperature_Change_df)

names(Temperature_Change_df)[c(1,2,5,6,7,8,11,12)] <- c('Temp_Change_Domain Code',
'Temp_Change_Domain',
'Temp_Change_Element Code',
'Temp_Change_Element',
'Temp_Change_Months Code',
'Temp_Change_Months',
'Temp_Change_Unit',
'Temp_Change_Value')

# names(Temperature_Change_df)
```

```{r}
# Forest_Fires_df
#dim(Forest_Fires_df)
# names(Forest_Fires_df)

names(Forest_Fires_df)[c(1,2,5,6,7,8,13,14)] <- c('Forest_Fires_Domain Code',
'Forest_Fires_Domain',
'Forest_Fires_Element Code',
'Forest_Fires_Element',
'Forest_Fires_Item Code',
'Forest_Fires_Item',
'Forest_Fires_Unit',
'Forest_Fires_Value')

# names(Forest_Fires_df)
```

```{r}
# Forest_Area_df
# dim(Forest_Area_df)
# names(Forest_Area_df)

names(Forest_Area_df)[c(1,2,5,6,7,8,13,14)] <- c('Forest_Area_Domain Code',
'Forest_Area_Domain',
'Forest_Area_Element Code',
'Forest_Area_Element',
'Forest_Area_Item Code',
'Forest_Area_Item',
'Forest_Area_Unit',
'Forest_Area_Value')

# names(Forest_Area_df)
```

```{r}
# Agri_Land_Used_df
# dim(Agri_Land_Used_df)
# names(Agri_Land_Used_df)
 
names(Agri_Land_Used_df)[c(1,2,5,6,7,8,11,12)] <- c('Agri_Land_Used_Domain Code',
'Agri_Land_Used_Domain',
'Agri_Land_Used_Element Code',
'Agri_Land_Used_Element',
'Agri_Land_Used_Item Code',
'Agri_Land_Used_Item',
'Agri_Land_Used_Unit',
'Agri_Land_Used_Value')

# names(Agri_Land_Used_df)
```

```{r}
# Social_And_Health_df
# dim(Social_And_Health_df)
# names(Social_And_Health_df)

# ****NOT CONSIDERED NEED TO TALK WITH TEAM ON THIS**** #
```

```{r}
#Credit_To_Agri_df
# dim(Credit_To_Agri_df)
# names(Credit_To_Agri_df)

names(Credit_To_Agri_df)[c(1,2,5,6,7,8,11,12)] <- c('Credit_To_Agri_Domain Code',
'Credit_To_Agri_Domain',
'Credit_To_Agri_Element Code',
'Credit_To_Agri_Element',
'Credit_To_Agri_Item Code',
'Credit_To_Agri_Item',
'Credit_To_Agri_Unit',
'Credit_To_Agri_Value')

# names(Credit_To_Agri_df)
```

```{r}
#Fertilizer_Indicators_df
# dim(Fertilizer_Indicators_df)
# names(Fertilizer_Indicators_df)


names(Fertilizer_Indicators_df)[c(1,2,5,6,7,8,11,12)] <- c('Fertilizer_Ind_Domain Code',
'Fertilizer_Ind_Domain',
'Fertilizer_Ind_Element Code',
'Fertilizer_Ind_Element',
'Fertilizer_Ind_Item Code',
'Fertilizer_Ind_Item',
'Fertilizer_Ind_Unit',
'Fertilizer_Ind_Value')

# names(Fertilizer_Indicators_df)
```

```{r}
#GDP_df
# dim(GDP_df)
# names(GDP_df)


names(GDP_df)[c(1,2,5,6,7,8,11,12)] <- c('GDP_Domain Code',
'GDP_Domain',
'GDP_Element Code',
'GDP_Element',
'GDP_Item Code',
'GDP_Item',
'GDP_Unit',
'GDP_Value')

# names(GDP_df)
```

```{r}

# remove columns
Emissions_CO2_NO2_df <- Emissions_CO2_NO2_df[, !colnames(Emissions_CO2_NO2_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]

Temperature_Change_df <- Temperature_Change_df[, !colnames(Temperature_Change_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]

Forest_Fires_df <- Forest_Fires_df[, !colnames(Forest_Fires_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]


Forest_Area_df <- Forest_Area_df[, !colnames(Forest_Area_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]


Agri_Land_Used_df <- Agri_Land_Used_df[, !colnames(Agri_Land_Used_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]


Credit_To_Agri_df <- Credit_To_Agri_df[, !colnames(Credit_To_Agri_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]


Fertilizer_Indicators_df <- Fertilizer_Indicators_df[, !colnames(Fertilizer_Indicators_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]


GDP_df <- GDP_df[, !colnames(GDP_df) %in% c('Flag', 'Flag Description', 'Note', 'Year Code', 'Source Code', 'Source')]


```



```{r}

# remove spaces in column names and replace with underscores
colnames(Emissions_CO2_NO2_df) <- gsub(" ", "_", colnames(Emissions_CO2_NO2_df))
colnames(Temperature_Change_df) <- gsub(" ", "_", colnames(Temperature_Change_df))
colnames(Forest_Fires_df) <- gsub(" ", "_", colnames(Forest_Fires_df))
colnames(Forest_Area_df) <- gsub(" ", "_", colnames(Forest_Area_df))
colnames(Agri_Land_Used_df) <- gsub(" ", "_", colnames(Agri_Land_Used_df))
colnames(Credit_To_Agri_df) <- gsub(" ", "_", colnames(Credit_To_Agri_df))
colnames(Fertilizer_Indicators_df) <- gsub(" ", "_", colnames(Fertilizer_Indicators_df))
colnames(GDP_df) <- gsub(" ", "_", colnames(GDP_df))


# remove parentheses in column names
colnames(Emissions_CO2_NO2_df) <- gsub("[()]", "", colnames(Emissions_CO2_NO2_df))
colnames(Temperature_Change_df) <- gsub("[()]", "", colnames(Temperature_Change_df))
colnames(Forest_Fires_df) <- gsub("[()]", "",colnames(Forest_Fires_df))
colnames(Forest_Area_df) <- gsub("[()]", "", colnames(Forest_Area_df))
colnames(Agri_Land_Used_df) <- gsub("[()]", "", colnames(Agri_Land_Used_df))
colnames(Credit_To_Agri_df) <- gsub("[()]", "",colnames(Credit_To_Agri_df))
colnames(Fertilizer_Indicators_df) <- gsub("[()]", "", colnames(Fertilizer_Indicators_df))
colnames(GDP_df) <- gsub("[()]", "",colnames(GDP_df))



```

```{r}
# create a list of data frames to be merged
df_list <- list(Temperature_Change_df, Emissions_CO2_NO2_df, Forest_Fires_df, Forest_Area_df, Agri_Land_Used_df, Credit_To_Agri_df, Fertilizer_Indicators_df, GDP_df)

for (i in 1:length(df_list)) {
  dim_i <- dim(df_list[[i]])
  cat("The dimensions of element", i, "are:", dim_i[1], " X ", dim_i[2], " \n")
}


```

# Merged all datasets into one
```{r}

# create a list of data frames to be merged
df_list <- list(Temperature_Change_df, Emissions_CO2_NO2_df, Forest_Fires_df, Forest_Area_df, Agri_Land_Used_df, Credit_To_Agri_df, Fertilizer_Indicators_df, GDP_df)

# merge the data frames using Reduce() and merge()
merged_data <- Reduce(function(x, y) merge(x, y, by = c("Year", "Area", "Area_Code_M49")), df_list)

# print the merged data frame
dim(merged_data)



```

```{r}

# create a CSV file from the merged data frame
# write.csv(merged_data, file = "/Users/sairam/Desktop/IIT files/Subjects/DPA CSP 571/merged_data.csv", row.names = FALSE)

```